# Generated by Django 6.0.4 on 2026-04-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payment_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
